version: '3.8'

services:

  database:
    image: mariadb:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: gestionarticle
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "8080:80"
    depends_on:
      - database

volumes:
  database_data:
