version: '3.9'

services:
  app:
    image: php:8.3-fpm
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - symfony_network
    environment:
      DATABASE_URL: "mysql://symfony:symfony@db:3306/symfony_db"
    depends_on:
      - db

  webserver:
    image: nginx:stable
    container_name: symfony_webserver
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony_network
    depends_on:
      - app

  db:
    image: mariadb:10.6
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_network

volumes:
  db_data:


networks:
  symfony_network:
