version: '3.9'

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8082:80"
    volumes:
      - ./:/code
      - ./nginx.conf:/etc/nginx/nginx.conf

  php:
    build: .
    volumes:
      - ./:/code

  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestionarticle
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - database

volumes:
  data:
